---
# tasks file for ansible-role-mysql-dump_all_databases

  - name: template in dump-all-databases.sh
    template:
      src: dump-all-databases.sh
      dest: "{{ mysql_dump_dest }}"
      owner: "{{ mysql_dump_owner }}"
      mode: "{{ mysql_dump_mode }}"
      backup: "{{ mysql_dump_backup }}"
    when: mysql_dump_enabled

  - name: ensure crontabs is installed on el
    yum: name=crontabs state=installed
    when: 
      - mysql_dump_cron_enabled
      - ansible_os_family == "RedHat"

  - name: create mysql_dump_store directory
    file: 
      path: "{{ mysql_dump_store }}"
      state: directory
      owner: "{{ mysql_dump_owner }}"
      mode: 0750
    when: 
      - mysql_dump_enabled
      - mysql_dump_cron_enabled

  - name: add cronjob to run the dump-all-script
    cron:
      name: "{{ item.name }}"
      minute: "{{ item.minute }}"
      hour: "{{ item.hour }}"
      day: "{{ item.day|default(omit) }}"
      month: "{{ item.month|default(omit) }}"
      weekday: "{{ item.weekday|default(omit) }}"
      user: "{{ item.user }}"
      job: "{{ item.job }}"
      cron_file: "{{ item.name }}"
      state: "{{ item.state|default(omit) }}"
    with_items: "{{ mysql_dump_cronjob }}"
    when: mysql_dump_cron_enabled

...
